### ISSUE TITLE
Show title from xkcd comics

### ISSUE THREAD

**Issue by jorgelamb** [adtac/relevant-xkcd#2]
XKCD comics always have some title with some extra joke or detail. It would be nice to have them in relevant-xkcd too, without having to go to xkcd itself.

**Comment by adtac** [comment]
I know, but I couldn't get the metadata from ExplainXKCD reliably. I think I'll simply scrap the title from each XKCD page (sorry Randall, you're about to get 1800 visits from a bot :P)

**Comment by jorgelamb** [comment]
Maybe you can start from here: https://github.com/itdaniher/bash-scripts-old/blob/master/xkcd.sh/xkcd_index

**Comment by jorgelamb** [comment]
Or here: http://peter.sh/wp-content/themes/default/examples/javascript/event-source-xkcd.txt

**Comment by adtac** [comment]
Those links are great but neither's complete (the max is ~#700). But the script at https://github.com/itdaniher/bash-scripts-old/tree/master/xkcd.sh seems to be useful.

**Comment by jorgelamb** [comment]
Nice! :+1: 

There are small issues with quotes in the title, as they break the html and the title is cut. For example, looking for "tables" the first one shown is https://xkcd.com/526 and the title is cut.

Cheers
